name: ptychography-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.7
  - mpi4py
  - dxchange
  - pip
  - pip:
    - numpy
    - pandas
    - autograd
    - matplotlib
    - jupyter
    - tqdm
